# K-Means Clustering with scikit-learn

We are going to use the implementation for k-means from scikit-learn, see [here](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans.fit) for a documentation. 

In [2]:
from sklearn.cluster import KMeans

When using k-means from scikit-learn, we recommend you that your data be stored as a numpy array. Create it or convert your data into a numpy array as follows.

In [3]:
import numpy as np

#create a numpy array
X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0]])

#convert a list to a numpy array
a=[]
for i in range(0,10):
    p=[i,2*i]
    a.append(p)

Y=np.array(a, dtype='float32')


The following execute the k-means algorithm on the points in X. Make sure you understand the parameters see [here](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans.fit)

In [4]:
kmeans = KMeans(init='random', n_clusters=2, max_iter=10000, n_init=100).fit(X)

The following code shows for each data points its cluster (0 or 1)

In [5]:
kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

The following code computes the clusters for the points [0,0] and [4,4]. In this case, [0,0] is placed in cluster labeled 0 and [4,4] in the cluster labeled 1.

In [6]:
kmeans.predict([[0, 0], [4, 4]])

array([1, 0], dtype=int32)

The following code shows the centroids (in this case called centers ) of the two clusters.

In [7]:
kmeans.cluster_centers_

array([[4., 2.],
       [1., 2.]])

# TP CLUSTERING

In [8]:
def distance(u,v):
    return (((u[0]-v[0])**2)+((u[1]-v[1])**2))**0.5

def SSE(tab,k):
    kmeans = KMeans(init='random', n_clusters=k, max_iter=10000, n_init=100).fit(tab)
    Somme_cluster=np.zeros(k)
    for i in tab:
        c=kmeans.labels_[i]
        center=kmeans.cluster_centers_[c]
        Somme_cluster[c]+=distance(i,center)
    return np.sum(Somme_cluster)
    
    

In [9]:
SSE(X,2)

15.12899020449196

In [51]:
def 

        
    

In [53]:
L=ouvrir_le_fichier('/home/paul/Bureau/data.csv')
print(L)

ValueError: could not convert string to float: American Express

In [45]:
def (L):
    A=[] 
    for i in range(1,len(L)):
        B=[j for j in L[i]]
        del B[0]
        A.append(B)
    
    return np.asarray(A)

In [37]:
L=adaptedList(L)

In [41]:
kmeans = KMeans(init='random', n_clusters=8, max_iter=10000, n_init=100).fit(L)

In [42]:
kmeans.labels_

array([2, 2, 3, 0, 6, 5, 6, 4, 7, 0, 7, 7, 2, 5, 0, 7, 1, 7, 7, 5, 5, 3,
       7, 3, 7, 2, 5, 5, 7, 5], dtype=int32)